services:
  - type: web
    name: bella-cucina-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bella-cucina-db
          property: connectionString

databases:
  - name: bella-cucina-db
    plan: free
