services:
  - type: web
    name: bella-cucina
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://schema_uez0_user:BVwbEKyvGYwKht8lJj0kncVbpTDA154p@dpg-cvslha6uk2gs73bpfohg-a/schema_uez0
      - key: PORT
        value: 3000

databases:
  - name: bella-cucina-db
    plan: free
