services:
  - type: web
    name: bella-cucina
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    healthCheckTimeout: 300
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bella-cucina-db
          property: connectionString
      - key: PORT
        value: 3000
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5

databases:
  - name: bella-cucina-db
    databaseName: schema_uez0
    plan: free
    ipAllowList: []
