services:
  - type: web
    name: bella-cucina
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    healthCheckTimeout: 300
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://schema_uez0_user:BVwbEKyvGYwKht8lJj0kncVbpTDA154p@dpg-cvslha6uk2gs73bpfohg-a/schema_uez0
      - key: PORT
        value: 3000
      - key: DB_MAX_CONNECTIONS
        value: 20
      - key: DB_IDLE_TIMEOUT_MS
        value: 60000
      - key: DB_CONNECTION_TIMEOUT_MS
        value: 10000
      - key: MAX_RETRIES
        value: 5
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    size: free

databases:
  - name: bella-cucina-db
    plan: free
