services:
  - type: web
    name: bella-cucina
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bella-cucina-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: bella-cucina-db
    plan: free
